packages:
  - "packages/*"
allowBuilds:
  esbuild: false
  sharp: false
  vue-demi: false
  workerd: false
patchedDependencies:
  '@cloudflare/vitest-pool-workers@0.12.21': patches/@cloudflare__vitest-pool-workers@0.12.21.patch
